### ISSUE TITLE
Proxy reveals real URLs in M3U8 file segmentation

### ISSUE THREAD

**Issue by OrionCodeDev** [DeveloperJosh/m3u8-proxy#2]
Problem Description
The current implementation of the proxy for fetching .m3u8 files exposes real links in the segmentation, creating a potential data leak. This issue allows anyone inspecting the .m3u8 file in the browser to easily identify the real URLs used by the proxy.

Example
When making a proxy request like this:

https://renewed-georgeanne-nekonode-1aa70c0c.koyeb.app/fetch?url=https://rumble.com/live-hls-dvr/5q596t/playlist.m3u8?
The proxy returns the .m3u8 file with segments like this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:1.0,
https://renewed-georgeanne-nekonode-1aa70c0c.koyeb.app/fetch/segment?url=https%3A%2F%2F1a-1791.com%2Flive%2Fu7gf26qm%2Fslot-86%2Fy96e-fzpl_1080p%2Fmedia-ui8kcld5l_DVR_0.ts
#EXTINF:2.0,
https://renewed-georgeanne-nekonode-1aa70c0c.koyeb.app/fetch/segment?url=https%3A%2F%2F1a-1791.com%2Flive%2Fu7gf26qm%2Fslot-86%2Fy96e-fzpl_1080p%2Fmedia-ui8kcld5l_DVR_1.ts
#EXTINF:2.0,
https://renewed-georgeanne-nekonode-1aa70c0c.koyeb.app/fetch/segment?url=https%3A%2F%2F1a-1791.com%2Flive%2Fu7gf26qm%2Fslot-86%2Fy96e-fzpl_1080p%2Fmedia-ui8kcld5l_DVR_2.ts
```
The url parameter within each segment reveals the real URLs, making it easy to access the original resource bypassing the proxy.

Suggested Improvement
To eliminate the data leak, the proxy server should implement encryption or tokenization for the segment URLs. This would obscure the real links, making it harder for anyone to extract them.

Possible Solutions
Tokenized Links:

Replace the url parameter with a unique, time-limited token that maps to the real URL server-side.
Example:
#EXTINF:1.0,
https://renewed-georgeanne-nekonode-1aa70c0c.koyeb.app/fetch/segment?token=abc123
Encrypted URLs:

Encrypt the real URL before embedding it in the m3u8 file.
Decrypt the URL server-side when the request is made.
Short-lived Signed URLs:

Use signed URLs that expire after a short duration.
Example:
#EXTINF:1.0,
https://renewed-georgeanne-nekonode-1aa70c0c.koyeb.app/fetch/segment?sig=xyz456&exp=1698761234

**Comment by DeveloperJosh** [comment]
Hi, I would spend more time working on this proxy, but as I mentioned on my GitHub page, I haven't been very active lately due to moving and starting college. If you'd like to take a shot at fixing any issues, feel free to fork the project and submit a pull request.

**Comment by DeveloperJosh** [comment]
I’ve implemented the changes to the proxy.
